name: Build Test

on:
  workflow_dispatch: # Manual trigger only
    inputs:
      platform:
        description: 'Platform to build for'
        required: true
        default: 'windows'
        type: choice
        options:
        - windows
        - macos
        - linux
        - all

jobs:
  build-windows:
    if: ${{ github.event.inputs.platform == 'windows' || github.event.inputs.platform == 'all' }}
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Node.js dependencies
      run: npm ci
      
    - name: Verify icon files
      run: npm run verify-icons
      
    - name: Build React app
      run: npm run build
      
    - name: Build Electron app for Windows
      run: npm run make:win64
      
    - name: Upload Windows build
      uses: actions/upload-artifact@v4
      with:
        name: FowCrawler-Windows-Test
        path: |
          out/make/squirrel.windows/**/*.exe
          out/make/squirrel.windows/**/*.nupkg
          out/make/zip/win32/**/*.zip
        retention-days: 7

  build-macos:
    if: ${{ github.event.inputs.platform == 'macos' || github.event.inputs.platform == 'all' }}
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Node.js dependencies
      run: npm ci
      
    - name: Verify icon files
      run: npm run verify-icons
      
    - name: Build React app
      run: npm run build
      
    - name: Build Electron app for macOS
      run: npm run make
      
    - name: Upload macOS build
      uses: actions/upload-artifact@v4
      with:
        name: FowCrawler-macOS-Test
        path: |
          out/make/zip/darwin/**/*.zip
        retention-days: 7

  build-linux:
    if: ${{ github.event.inputs.platform == 'linux' || github.event.inputs.platform == 'all' }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Node.js dependencies
      run: npm ci
      
    - name: Verify icon files
      run: npm run verify-icons
      
    - name: Build React app
      run: npm run build
      
    - name: Build Electron app for Linux
      run: npm run make
      
    - name: Upload Linux build
      uses: actions/upload-artifact@v4
      with:
        name: FowCrawler-Linux-Test
        path: |
          out/make/deb/**/*.deb
          out/make/rpm/**/*.rpm
          out/make/zip/linux/**/*.zip
        retention-days: 7 